# Generated by Django 3.2.5 on 2021-07-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_prize_prodcut_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prodcut',
            new_name='product',
        ),
    ]
