# Generated by Django 3.2.4 on 2021-07-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='des',
            new_name='des1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
